## Productionisation (Model Deserialization)

In [1]:
import numpy as np
from pickle import load

In [2]:
# Loading pretrained classifiers from pickle file

scaler = load(open('C:/Users/user/Desktop/Internship Data Science 2023/titanic_survival_prediction/models/standard_scaler.pkl', 'rb'))
knn_classifier = load(open('C:/Users/user/Desktop/Internship Data Science 2023/titanic_survival_prediction/models/knn_model.pkl', 'rb'))
lr_classifier = load(open('C:/Users/user/Desktop/Internship Data Science 2023/titanic_survival_prediction/models/lr_model.pkl', 'rb'))
nb_classifier = load(open('C:/Users/user/Desktop/Internship Data Science 2023/titanic_survival_prediction/models/nb_model.pkl', 'rb'))
dt_classifier = load(open('C:/Users/user/Desktop/Internship Data Science 2023/titanic_survival_prediction/models/dt_model.pkl', 'rb'))
sv_classifier = load(open('C:/Users/user/Desktop/Internship Data Science 2023/titanic_survival_prediction/models/sv_model.pkl', 'rb'))

In [3]:
# Read the Query Data

print("Enter the Person Details(in numerical)")
Age = float(input('Enter Age: '))
Fare = float(input('Enter Fare: '))
Pclass_1 = float(input('Enter 1(if the person belongs to class 1) otherwise 0: '))
Pclass_2 = float(input('Enter 1(if the person belongs to class 2) otherwise 0: '))
Pclass_3 = float(input('Enter 1(if the person belongs to class 3) otherwise 0: '))
Sex_female = float(input('Enter 1(if the person is female) otherwise 0: '))
Sex_male = float(input('Enter 1(if the person is male) otherwise 0: '))
SibSp_0 = float(input('Enter 1(if the person belongs to SibSp_0) otherwise 0: '))
SibSp_1 = float(input('Enter 1(if the person belongs to SibSp_1) otherwise 0: '))
SibSp_2 = float(input('Enter 1(if the person belongs to SibSp_2) otherwise 0: '))
SibSp_3 = float(input('Enter 1(if the person belongs to SibSp_3) otherwise 0: '))
SibSp_4 = float(input('Enter 1(if the person belongs to SibSp_4) otherwise 0: '))
SibSp_5 = float(input('Enter 1(if the person belongs to SibSp_5) otherwise 0: '))
SibSp_8 = float(input('Enter 1(if the person belongs to SibSp_8) otherwise 0: '))
Parch_0 = float(input('Enter 1(if the person belongs to Parch_0) otherwise 0: '))
Parch_1 = float(input('Enter 1(if the person belongs to Parch_1) otherwise 0: '))
Parch_2 = float(input('Enter 1(if the person belongs to Parch_2) otherwise 0: '))
Parch_3 = float(input('Enter 1(if the person belongs to Parch_3) otherwise 0: '))
Parch_4 = float(input('Enter 1(if the person belongs to Parch_4) otherwise 0: '))
Parch_5 = float(input('Enter 1(if the person belongs to Parch_5) otherwise 0: '))
Parch_6 = float(input('Enter 1(if the person belongs to Parch_6) otherwise 0: '))
Embarked_C = float(input('Enter 1(if the person belongs to Embarked_C) otherwise 0: '))
Embarked_Q = float(input('Enter 1(if the person belongs to Embarked_Q) otherwise 0: '))
Embarked_S = float(input('Enter 1(if the person belongs to Embarked_S) otherwise 0: '))

Enter the Person Details(in numerical)
Enter Age: 32
Enter Fare: 7.75
Enter 1(if the person belongs to class 1) otherwise 0: 0
Enter 1(if the person belongs to class 2) otherwise 0: 0
Enter 1(if the person belongs to class 3) otherwise 0: 1
Enter 1(if the person is female) otherwise 0: 0
Enter 1(if the person is male) otherwise 0: 1
Enter 1(if the person belongs to SibSp_0) otherwise 0: 1
Enter 1(if the person belongs to SibSp_1) otherwise 0: 0
Enter 1(if the person belongs to SibSp_2) otherwise 0: 0
Enter 1(if the person belongs to SibSp_3) otherwise 0: 0
Enter 1(if the person belongs to SibSp_4) otherwise 0: 0
Enter 1(if the person belongs to SibSp_5) otherwise 0: 0
Enter 1(if the person belongs to SibSp_8) otherwise 0: 0
Enter 1(if the person belongs to Parch_0) otherwise 0: 1
Enter 1(if the person belongs to Parch_1) otherwise 0: 0
Enter 1(if the person belongs to Parch_2) otherwise 0: 0
Enter 1(if the person belongs to Parch_3) otherwise 0: 0
Enter 1(if the person belongs to Parch

In [4]:
query_point = np.array([Age, Fare, Pclass_1, Pclass_2, Pclass_3, Sex_female, Sex_male, SibSp_0, SibSp_1, SibSp_2, SibSp_3, SibSp_4, SibSp_5, SibSp_8, Parch_0, Parch_1, Parch_2, Parch_3, Parch_4, Parch_5, Parch_6, Embarked_C, Embarked_Q, Embarked_S])

In [5]:
query_point

array([32.  ,  7.75,  0.  ,  0.  ,  1.  ,  0.  ,  1.  ,  1.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ])

In [6]:
query_point = query_point.reshape(1, -1)

query_point

array([[32.  ,  7.75,  0.  ,  0.  ,  1.  ,  0.  ,  1.  ,  1.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ]])

In [7]:
query_point_transformed = scaler.transform(query_point)

query_point_transformed

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 0.16520151, -0.48668949, -0.56813051, -0.51027185,  0.90562878,
        -0.72705166,  0.72705166,  0.67713757, -0.54505723, -0.18883568,
        -0.12327842, -0.14088055, -0.07761505, -0.1029078 ,  0.56351951,
        -0.38183452, -0.32551538, -0.08684168, -0.05479966, -0.07761505,
        -0.03872015, -0.45841567,  3.1832897 , -1.67196129]])

In [8]:
knn_classifier.predict(query_point_transformed)

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [9]:
lr_classifier.predict(query_point_transformed)

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [10]:
nb_classifier.predict(query_point_transformed)

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [11]:
dt_classifier.predict(query_point_transformed)

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [12]:
sv_classifier.predict(query_point_transformed)

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

### Production Ready Code

In [13]:
# Read the Query Data

print("Enter the Person Details(in numerical)")
Age = float(input('Enter Age: '))
Fare = float(input('Enter Fare: '))
Pclass_1 = float(input('Enter 1(if the person belongs to class 1) otherwise 0: '))
Pclass_2 = float(input('Enter 1(if the person belongs to class 2) otherwise 0: '))
Pclass_3 = float(input('Enter 1(if the person belongs to class 3) otherwise 0: '))
Sex_female = float(input('Enter 1(if the person is female) otherwise 0: '))
Sex_male = float(input('Enter 1(if the person is male) otherwise 0: '))
SibSp_0 = float(input('Enter 1(if the person belongs to SibSp_0) otherwise 0: '))
SibSp_1 = float(input('Enter 1(if the person belongs to SibSp_1) otherwise 0: '))
SibSp_2 = float(input('Enter 1(if the person belongs to SibSp_2) otherwise 0: '))
SibSp_3 = float(input('Enter 1(if the person belongs to SibSp_3) otherwise 0: '))
SibSp_4 = float(input('Enter 1(if the person belongs to SibSp_4) otherwise 0: '))
SibSp_5 = float(input('Enter 1(if the person belongs to SibSp_5) otherwise 0: '))
SibSp_8 = float(input('Enter 1(if the person belongs to SibSp_8) otherwise 0: '))
Parch_0 = float(input('Enter 1(if the person belongs to Parch_0) otherwise 0: '))
Parch_1 = float(input('Enter 1(if the person belongs to Parch_1) otherwise 0: '))
Parch_2 = float(input('Enter 1(if the person belongs to Parch_2) otherwise 0: '))
Parch_3 = float(input('Enter 1(if the person belongs to Parch_3) otherwise 0: '))
Parch_4 = float(input('Enter 1(if the person belongs to Parch_4) otherwise 0: '))
Parch_5 = float(input('Enter 1(if the person belongs to Parch_5) otherwise 0: '))
Parch_6 = float(input('Enter 1(if the person belongs to Parch_6) otherwise 0: '))
Embarked_C = float(input('Enter 1(if the person belongs to Embarked_C) otherwise 0: '))
Embarked_Q = float(input('Enter 1(if the person belongs to Embarked_Q) otherwise 0: '))
Embarked_S = float(input('Enter 1(if the person belongs to Embarked_S) otherwise 0: '))

query_point = np.array([Age, Fare, Pclass_1, Pclass_2, Pclass_3, Sex_female, Sex_male, SibSp_0, SibSp_1, SibSp_2, SibSp_3, SibSp_4, SibSp_5, SibSp_8, Parch_0, Parch_1, Parch_2, Parch_3, Parch_4, Parch_5, Parch_6, Embarked_C, Embarked_Q, Embarked_S]).reshape(1, -1)
query_point_transformed = scaler.transform(query_point)
lr_classifier.predict(query_point_transformed)

Enter the Person Details(in numerical)
Enter Age: 32
Enter Fare: 7.75
Enter 1(if the person belongs to class 1) otherwise 0: 0
Enter 1(if the person belongs to class 2) otherwise 0: 0
Enter 1(if the person belongs to class 3) otherwise 0: 1
Enter 1(if the person is female) otherwise 0: 0
Enter 1(if the person is male) otherwise 0: 1
Enter 1(if the person belongs to SibSp_0) otherwise 0: 1
Enter 1(if the person belongs to SibSp_1) otherwise 0: 0
Enter 1(if the person belongs to SibSp_2) otherwise 0: 0
Enter 1(if the person belongs to SibSp_3) otherwise 0: 0
Enter 1(if the person belongs to SibSp_4) otherwise 0: 0
Enter 1(if the person belongs to SibSp_5) otherwise 0: 0
Enter 1(if the person belongs to SibSp_8) otherwise 0: 0
Enter 1(if the person belongs to Parch_0) otherwise 0: 1
Enter 1(if the person belongs to Parch_1) otherwise 0: 0
Enter 1(if the person belongs to Parch_2) otherwise 0: 0
Enter 1(if the person belongs to Parch_3) otherwise 0: 0
Enter 1(if the person belongs to Parch

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)